interface ArticleInterface {
  id: ID!
  title: String!
}

interface ResponseInterface {
  error: Error
}

type Author implements ArticleInterface {
  id: ID!
  title: String!
  user: User! @provides(fields: "email")
}

type Review {
  id: ID!
  rating: Int!
  comments: String!
}

type Reviews implements ArticleInterface {
  id: ID!
  title: String!
  reviews: [Review!]!
}

input ArticleInput {
  title: String!
}

type ArticleById implements ResponseInterface {
  error: Error
  data: ArticleInterface
}

type Articles implements ResponseInterface {
  error: Error
  data: [ArticleInterface]!
}

type Query {
  article(articleId: ID!): ArticleById!
  articles: Articles!
}

type NewArticle {
  status: String!
  id: ID!
}

type CreateArticle {
  error: Error
  data: NewArticle
}

type Mutation {
  createArticle(input: ArticleInput!): CreateArticle
}
